/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SEPackage;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Sudhanshu's
 */
public class StartGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    public StartGUI() throws IOException {
        initComponents();
        setPlayerScrollPanel();
        


        ResultSet rs = null;
        DatabaseConnection db = new DatabaseConnection();
        rs = db.getPlayerStatistics("Sachin Tendulkar", "2008");
        try {
            while(rs.next()){
                String name = rs.getString("name");
                int runs = rs.getInt(4);
                int wickets = rs.getInt(5);
                int num_of_innings = rs.getInt(6);
                float bat_strikerate = rs.getFloat(7);
                float bowl_strikerate = rs.getFloat(8);
                float batting_average = rs.getFloat(9);
                float bowling_average = rs.getFloat(10);
                float economy = rs.getFloat(11);
                int number_of_fifties = rs.getInt(12);
                int number_of_centuries = rs.getInt(13);
                float base_price = rs.getFloat(14);
                
                System.out.println("Person name : "+name);
                System.out.println("Runs : "+Integer.toString(runs));
                System.out.println("Wickets : "+Integer.toString(wickets));
                System.out.println("Number of Innings : "+Integer.toString(num_of_innings));
                System.out.println("Batting Strike rate : "+Float.toString(bat_strikerate));
                System.out.println("Bowling Strike rate : "+Float.toString(bowl_strikerate));
                System.out.println("Batting Average : "+Float.toString(batting_average));
                System.out.println("Bowling Average : "+Float.toString(bowling_average));
                System.out.println("Economy : "+Float.toString(economy));
                System.out.println("Number of 50's : "+Integer.toString(number_of_fifties));
                System.out.println("Number of 100's : "+Integer.toString(number_of_centuries));
                System.out.println("Base Price : "+Float.toString(base_price));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Main = new javax.swing.JPanel();
        TP = new javax.swing.JTabbedPane();
        ScrollPane_Player = new javax.swing.JScrollPane();
        Panel_Player = new javax.swing.JPanel();
        ScrollPane_Owner = new javax.swing.JScrollPane();
        Panel_Owner = new javax.swing.JPanel();
        ScrollPane_Team = new javax.swing.JScrollPane();
        Panel_Team = new javax.swing.JPanel();
        TF_Search = new javax.swing.JTextField();
        B_Search = new javax.swing.JLabel();
        Bg1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TP.setVerifyInputWhenFocusTarget(false);
        TP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPMouseClicked(evt);
            }
        });

        ScrollPane_Player.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScrollPane_PlayerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_PlayerLayout = new javax.swing.GroupLayout(Panel_Player);
        Panel_Player.setLayout(Panel_PlayerLayout);
        Panel_PlayerLayout.setHorizontalGroup(
            Panel_PlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        Panel_PlayerLayout.setVerticalGroup(
            Panel_PlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        ScrollPane_Player.setViewportView(Panel_Player);

        TP.addTab("        Player        ", ScrollPane_Player);

        javax.swing.GroupLayout Panel_OwnerLayout = new javax.swing.GroupLayout(Panel_Owner);
        Panel_Owner.setLayout(Panel_OwnerLayout);
        Panel_OwnerLayout.setHorizontalGroup(
            Panel_OwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        Panel_OwnerLayout.setVerticalGroup(
            Panel_OwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        ScrollPane_Owner.setViewportView(Panel_Owner);

        TP.addTab("           Owner          ", ScrollPane_Owner);

        javax.swing.GroupLayout Panel_TeamLayout = new javax.swing.GroupLayout(Panel_Team);
        Panel_Team.setLayout(Panel_TeamLayout);
        Panel_TeamLayout.setHorizontalGroup(
            Panel_TeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        Panel_TeamLayout.setVerticalGroup(
            Panel_TeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        ScrollPane_Team.setViewportView(Panel_Team);

        TP.addTab("           Team          ", ScrollPane_Team);

        Panel_Main.add(TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 300, 517));

        TF_Search.setText("Search..");
        TF_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_SearchActionPerformed(evt);
            }
        });
        Panel_Main.add(TF_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 251, 30));

        B_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/image/search.png"))); // NOI18N
        Panel_Main.add(B_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 0, -1, 30));

        Bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/image/ipl-2015-background.jpg"))); // NOI18N
        Panel_Main.add(Bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, -6, 850, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/image/Bg_2.png"))); // NOI18N
        Panel_Main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_SearchActionPerformed
    
    public ArrayList<String> listFilesForFolder(final File folder) {
        ArrayList<String> lists=new ArrayList<String>();
        for (final File fileEntry : folder.listFiles()) {
        if (fileEntry.isDirectory()) {
            listFilesForFolder(fileEntry);
        } else {
            lists.add(fileEntry.getName());
        }
    }
        return lists;
}
    
    private void TPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPMouseClicked
        
    }//GEN-LAST:event_TPMouseClicked

    private void ScrollPane_PlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPane_PlayerMouseClicked

    }//GEN-LAST:event_ScrollPane_PlayerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StartGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_Search;
    private javax.swing.JLabel Bg1;
    private javax.swing.JLayeredPane LayeredPane_Owner;
    private javax.swing.JLayeredPane LayeredPane_Owner1;
    private javax.swing.JLayeredPane LayeredPane_Owner2;
    private javax.swing.JLayeredPane LayeredPane_Player;
    private javax.swing.JLayeredPane LayeredPane_Player1;
    private javax.swing.JLayeredPane LayeredPane_Player2;
    private javax.swing.JLayeredPane LayeredPane_Team;
    private javax.swing.JLayeredPane LayeredPane_Team1;
    private javax.swing.JLayeredPane LayeredPane_Team2;
    private javax.swing.JPanel Panel_Main;
    private javax.swing.JPanel Panel_Owner;
    private javax.swing.JPanel Panel_Player;
    private javax.swing.JPanel Panel_Start;
    private javax.swing.JPanel Panel_Start1;
    private javax.swing.JPanel Panel_Start2;
    private javax.swing.JPanel Panel_Team;
    private javax.swing.JScrollPane ScrollPane_Owner;
    private javax.swing.JScrollPane ScrollPane_Player;
    private javax.swing.JScrollPane ScrollPane_Team;
    private javax.swing.JTextField TF_Search;
    private javax.swing.JTabbedPane TP;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTabbedPane TabbedPane1;
    private javax.swing.JTabbedPane TabbedPane2;
    private javax.swing.JTextField TextField_Search;
    private javax.swing.JTextField TextField_Search1;
    private javax.swing.JTextField TextField_Search2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void setPlayerScrollPanel() throws IOException {
        final File folder = new File(".\\Images\\");
        ArrayList<String> lists=listFilesForFolder(folder);
        int len=lists.size(),count=0,padd_hor=90,padd_ver=90;
        int col=3,row=(lists.size()/col)+1;
        JLabel label[][]=new JLabel[row][col];
        System.out.println(len);
        for(int i=0;i<row&&count<len;i++)
        {
            for(int j=0;j<col&&count<len;j++,count++)
            {
                BufferedImage img = null;
                img = ImageIO.read(new File(".\\Images\\"+lists.get(i)));
                Image dimg = img.getScaledInstance(50, 50,Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(dimg);
                label[i][j] = new JLabel();
                int posx,posy;
                if(j==0)
                    posx=20;
                else
                    posx=label[i][j-1].getX()+padd_hor;
                if(i==0)
                    posy=20;
                else
                    posy=label[i-1][j].getY()+padd_ver;
                label[i][j].setBounds(posx,posy,50,50);
                label[i][j].setIcon(icon);
                JLabel name=new JLabel(lists.get(i),SwingConstants.CENTER);
                name.setBounds(posx-10,posy+52,70,15);
                name.setFont(new Font("Comic Sans MS", Font.PLAIN, 10));
                name.setForeground(Color.BLACK);
                Panel_Player.add(name);
                Panel_Player.add(label[i][j]);

                }
                if(count>=len)
                break;
            }
            ScrollPane_Player.updateUI();
            ScrollPane_Player.setVisible(true);
            Panel_Player.updateUI();
            Panel_Player.setVisible(true);
    }
}
